[base]
log_level = "DEBUG"
debug = false
"职业技能按键" = "v"
"未充能近战按键" = "c"
"跳隐身按键" = "x"
"终结技按键" = "g"
"埋头表情按键" = "down" # 引号里可以填写up/right/down/left

"x技能识别阈值" = 0.8


[1440p]
"开boss鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 0.5
"隐身后往前走时间" = 1.83

"射击黄血鼠标偏移" = [188, 72]
"等待黄血刷新时间" = 5.805

"躲藏第一段位移镜头偏移" = [-850, 0]
"躲藏第一段位移时间" = 1.8

"躲藏第二段位移镜头偏移" = [250, 0]
"躲藏第二段位移时间" = 3

"终结失败后等待时间" = 25
"终结成功后等待时间" = 2
"未终结职业技能隐身后回近战时间" = 1.5


[1080p]
"开boss鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 0.5
"隐身后往前走时间" = 1.83

"射击黄血鼠标偏移" = [188, 72]
"等待黄血刷新时间" = 5.805

"躲藏第一段位移镜头偏移" = [-850, 0]
"躲藏第一段位移时间" = 1.8

"躲藏第二段位移镜头偏移" = [250, 0]
"躲藏第二段位移时间" = 3

"终结失败后等待时间" = 25
"终结成功后等待时间" = 2
"未终结职业技能隐身后回近战时间" = 1.5